JIKAN_API_HOST = "api.jikan.moe"
JIKAN_API_VERSION = "/v3"

DIR_LIST = [
    "devops/devops-links.MD",
    "algorithms/algorithms-links.MD",
    "dev/dev-links.MD",
    "linux/linux-links.MD",
    "other/other-links.MD"
]
COMMIT_SUBMISSION_FORMAT = """#<tags>
#title: [<title>]
#gitpath: [<path>]
#link: [<link>]"""

METHODS= {"search" : "/search"}
ANIME_GENRE = {
    'Action' : 1,
    'Adventure': 2,
    'Cars':3,
    'Comedy':4,
    'Dementia': 5,
    'Demons':6,
    'Mystery': 7,
    'Drama': 8,
    'Ecchi':9,
    'Fantasy': 10,
    'Game': 11,
    'Hentai': 12,
    'Historical': 13,
    'Horror': 14,
    'Kids': 15,
    'Magic': 16,
    'Martial Arts': 17,
    'Mecha': 18,
    'Music': 19,
    'Parody': 20,
    'Samurai': 21,
    'Romance': 22,
    'School': 23,
    'Sci Fi': 24,
    'Shoujo': 25,
    'Shoujo Ai': 26,
    'Shounen': 27,
    'Shounen Ai': 28,
    'Space': 29,
    'Sports': 30,
    'Super Power': 31,
    'Vampire': 32,
    'Yaoi': 33,
    'Yuri': 34,
    'Harem': 35,
    'Slice Of Life': 36,
    'Supernatural': 37,
    'Military': 38,
    'Police': 39,
    'Psychological': 40,
    'Thriller': 41,
    'Seinen': 42,
    'Josei':43
}

ANIME_TYPES=['tv', 'ova', 'movie', 'special', 'ona', 'music']
ANIME_STATUS=['airing', 'completed', 'complete', 'to_be_aired', 'tba', 'upcoming']
ANIME_RATED={
    'g': 'G - All Ages',
    'pg': 'PG - Children',
    'pg13': 'PG-13 - Teens 13 or older',
    'r17': 'R - 17+ recommended (violence & profanity)',
    'r': 'R+ - Mild Nudity (may also contain violence & profanity)',
    'rx': 'Rx - Hentai (extreme sexual content/nudity)'
}

GIN_LIST = ["You Guys!! Do You Even Have Gintama?!",
"Nobody With Naturally Wavy Hair Can Be That Bad",
"Watch Out!  Sometimes Comes Out On Saturdays!",
"Make Friends You Can Call By Their Nicknames, Even When You're An Old Fart",
"Keep Your Promise Even If It Kills You",
"Responsible Owners Should Clean Up After Their Pets",
"There Is Butt A Fine Line Between Persistence And Stubbornness",
"Fighting Should Be Done With Fists",
"Eat Something Sour When You're Tired",
"Look, Overly Sticky Sweet Dumplings Are Not Real Dumplings, You Idiot!",
"People Who Make Good First Impressions Usually Suck",
"If You're Going To Cosplay, Go All Out",
"Boys Have A Weird Ritual That Makes Them Think They Turn Into Men When They Touch A Frog""You Only Gotta Wash Under Your Armpits - Just The Armpits",
"Pets Resemble Their Owners",
"If You Stop And Think About It, Your Life's A Lot Longer As An Old Guy Than A Kid! Whoa, Scary!",
"Sons Only Take After Their Fathers' Negative Attributes",
"Oh, Yeah! Our Crib Is Number One!",
"Why Is The Sea So Salty? Because You City Folk Pee Whenever You Go Swimming!",
"Watch Out For Conveyor Belts!",
"If You're A Man, Try The Swordfish!""If You Go To Sleep With The Fan On You'll Get A Stomachache, So Be Careful",
"Marriage Is Prolonging An Illusion For Your Whole Life",
"When You're In A Fix, Keep On Laughing, Laughing...",
"Cute Faces Are Always Hiding Something",
"A Shared Soup Pot Is A Microcosm Of Life",
"Don't Be Shy - Just Raise Your Hand And Say It",
"Some Things Can't Be Cut With A Sword",
"Good Things Never Come In Twos (But Bad Things Do)",
"Don't Panic - There's A Return Policy!""I Told You To Pay Attention To The News!",
"Even Teen Idols Act Like You Guys",
"You Always Remember The Things That Matter The Least",
"Life Moves On Like A Conveyor Belt",
"Mistaking Someone's Name Is Rude!",
"Love Doesn't Require A Manual",
"Love Doesn't Require A Manual (Continued)""You Can't Judge A Person By His Appearance, Either",
"People With Dark Pasts Can't Shut Up",
"People Who Say That Santa Doesn't Really Exist Actually Want To Believe In Him""Prayer Won't Make Your Worldly Desires Go Away! Control Yourself",
"Only Children Play In The Snow""Eating Ice Cream In Winter Is Awesome",
"Ramen Shops With Long Menus Never Do Well",
"Give A Thought To Planned Pregnancy",
"You Can't Judge A Movie By Its Title",
"You Know What Happens If You Pee On A Worm",
"Make Characters So Anybody Can Tell Who They Are By Just Their Silhouettes""Since It Ended A Bit Early, We're Starting The Next One",
"Mom's Busy, Too, So Quit Complaining About What's For Dinner",
"Walk Your Dog At An Appropriate Speed",
"Adults Only. We Wouldn't Want Anyone Immature In Here...",
"Do Cherries Come From Cherry Trees?",
"The More You're Alike, The More You Fight""Whatever You Play, Play To Win",
"A Life Without Gambling Is Like Sushi Without Wasabi",
"Pending Means Pending, It's Not Final",
"Milk Should Be Served At Body Temperature",
"If You Want To See Someone, Make An Appo First",
"Stress Makes You Bald, But It's Stressful To Avoid Stress, So You End Up Stressed Out Anyway, So In The End There's Nothing You Can Do",
"Mothers Everywhere Are All The Same",
"Don't Make Munching Noises When You Eat",
"Keep An Eye On The Chief For The Day",
"When Looking For Things You've Lost, Remember What You Were Doing On The Day You Lost It",
"Croquette Sandwiches Are Always The Most Popular Food Sold At The Stalls",
"Be Careful Not To Leave Your Umbrella Somewhere",
"The Sun Will Rise Again",
"On A Moonless Night, Insects Are Drawn To The Light",
"Even Mummy Hunters Sometimes Turn Into Mummys",
"The Preview Section In JUMP Is Always Unreliable",
"Eating Nmaibo Can Make You Full In No Time!",
"Rhinoceros Beetles Teach Boys That Life Is Precious",
"Dango Over Flowers",
"For The Wind Is The Life""The Ideal Girlfriend Is Always Minami",
"Like A Haunted House, Life Is Filled With Horrors",
"Please Help By Separating Your Trash",
"Too Many Cuties Can Make You Sick",
"Some Data Cannot Be Erased",
"A Dog's Paws Smell Fragrant""Drive With A 'Might' Attitude",
"Think For A Minute Now, Do Matsutake Mushrooms Really Taste All That Good?",
"The Manga Writer Becomes A Pro, After Doing A Stock Of Manuscripts",
"Don't Complain About Your Job At Home, Do It Somewhere Else",
"In Those Situations, Keep Quiet And Cook Red Rice With Beans",
"Yesterday's Enemy, After All Is Said And Done, Is Still The Enemy",
"People Who Are Picky About Food Are Also Picky About People, Too",
"Four Heads Are Better Than One",
"When Someone Who Wears Glasses Takes Them Off, It Looks Like Something's Missing",
"A Woman's Best Make Up Is Her Smile",
"You Don't Stand In Line For The Ramen, You Stand In Line For The Self Satisfaction""You Say Kawaii So Often, You Must Really Think You're Cute Stuff",
"Rank Has Nothing To Do With Luck",
"Hard-Boiled Egg On A Man's Heart",
"Hard-Boiled Eggs Don't Crack",
"It's Often Difficult To Sleep When You're Engrossed With Counting Sheep",
"Perform A German Suplex On A Woman Who Asks If She Or The Job Is More Important",
"The Most Exciting Part Of A Group Date Is Before It Starts",
"What Happens Twice, Happens Thrice",
"The More Delicious The Food, The Nastier It Is When It Goes Bad",
"If You Want To Lose Weight, Then Stop Eating And Start Moving",
"Be A Person Who Can See People's Strong Points And Not Their Weak Points",
"Even A Hero Has Issues",
"When Riding A Train, Make Sure You Grab The Straps With Both Hands",
"Men, Be A Madao",
"If You're A Man, Don't Give Up",
"Exaggerate The Tales Of Your Exploits By A Third, So Everyone Has A Good Time""Men Have A Weakness For Girls Who Sell Flowers And Work In Pastry Shops",
"Play Video Games For Only An Hour A Day",
"Life And Video Games Are Full Of Bugs",
"The More Something Is Disliked, The More Lovely It Is",
"Rules Are Made To Be Broken",
"Otaku Are Talkative",
"There's A Thin Line Between Strengths And Weaknesses",
"Important Things Are Hard To See",
"It's All About The Beat And Timing",
"Love Is Often Played Out In Sudden Death",
"Kids Don't Understand How Their Parents Feel",
"Some Things Are Better Left Unsaid",
"Life Is A Test",
"People Are All Escapees Of Their Own Inner Prisons",
"Definitely Do Not Let Your Girlfriend See The Things You Use For Cross-Dressing""There's Almost A 100% Chance You'll Forget Your Umbrella And Hate Yourself For It",
"Lucky Is A Man Who Gets Up And Goes To Work",
"Cleaning The Toilet Cleanses The Soul",
"They Say Soy Sauce On Pudding Tastes Like Sea Urchin, But Soy Sauce On Pudding Only Tastes Like Pudding And Soy Sauce",
"Summer Vacation Is The Most Fun Right Before It Begins",
"The Older, The Wiser",
"Beauty Is Like A Summer Fruit",
"Even If Your Back Is Bent, Go Straight Forward",
"Within Each Box Of Cigarettes, Are One Or Two Cigarettes That Smell Like Horse Dung",
"Japanese Restaurants Abroad Taste Pretty Much Like School Cafeteria Lunches""Once You've Taken A Dish, You Can't Put It Back",
"Novices Only Need A Flathead And A Phillips",
"Imagination Is Nurtured In The 8th Grade",
"Always Keep A Screwdriver In Your Heart",
"When Nagging Goes Too Far It Becomes Intimidating",
"Entering The Final Chapter!",
"Some Things Can Only Be Conveyed Through The Written Word",
"Sometimes You Must Meet To Understand",
"Sometimes You Can't Tell Just By Meeting Someone",
"Beware Of Food You Pick Up Off The Ground",
"Cat Lovers And Dog Lovers Are Mutually Exclusive",
"Fights Often Ensue During Trips",
"Briefs Will Unavoidably Get Skidmarks",
"Gin And His Excellency's Good-For-Nothings",
"Be Very Careful When Using Ghost Stories",
"Before Thinking About The Earth, Think About The More Endangered Gintaman's Future!",
"It's Your House, You Build It",
"99% Of Men Aren't Confident In Confessing Their Love""People Who Don't Believe In Santa Are The Very Ones Who Want To Believe, You Contentious Bastard",
"Let's Talk About The Old Days Once In A While",
"Don't Put Your Wallet In Your Back Pocket",
"Beware Of Those Who Use An Umbrella On A Sunny Day!",
"Butting Into A Fight Is Dangerous",
"Life Is About Making Consecutive Decisions",
"Those Who Stand On Four Legs Are Beasts. Those Who Stand On Two Legs, Guts, And Glory Are Men",
"Don't Trust Bedtime Stories",
"The Color For Each Person's Bond Comes In Various Colors",
"The Taste Of Drinking Under Broad Daylight Is Something Special",
"All Adults Are Instructors For All Children",
"Zip Up Your Fly Nice And Slowly",
"When Breaking A Chuubert In Half, The End With The Knob Should Be Better. It's Also Tasty To Drink From There",
"If You Can't Beat Them, Join Them",
"A Conversation With A Barber, During A Haircut, Is The Most Pointless Thing In The World",
"The Heavens Created Chonmage Above Man Instead Of Another Man",
"Sleep Helps A Child Grow",
"That Person Looks Different From Usual During A Birthday Party",
"The Other Side Of The Other Side Of The Other Side Would Be The Other Side",
"It Takes A Bit Of Courage To Enter A Street Vendor's Stand",
"Any Place With Can Become a Battlefield When Men Gather",
"If A Friend Gets Injured, Take Him To The Hospital, Stat!",
"If One Orange In The Box Is Rotten, The Rest Of Them Will Become Rotten Before You Realize It",
"From A Foreigner's Perspective, You're The Foreigner. From An Alien's Perspective, You're The Alien",
"Laputa's Still Good After Seeing It So Many Times",
"Love Is Unconditional",
"The Black Ships Even Make A Scene When They Sink",
"That Matsutake Soup Stuff Tastes Better Than The Real Deal""If a Person Is Dead, They Can't Come Back To Life",
"If It Works Once, It'll Work Over And Over Again",
"Two Is Better Than One. Two People Are Better Than One",
"Smooth Polygons Smooth Men's Hearts Too",
"The Human Body Is Like A Little Universe",
"The Chosen Idiots",
"And Into The Legend...",
"If You Keep Copying, They Will Retaliate""A Loss Open Your Eyes To The Love You Have",
"Using The 'Carrot And Stick' Method Depends On The Situation",
"It's What's On The Inside That Counts""It's What's On The Inside That Counts, But Only To A Certain Extent",
"Are There Still People Who Go To The Ocean And Yell Out 'Bakayaro'?""When A Person Is Trapped, Their Inner Door Opens",
"No Matter How Old You Get, You Still Hate The Dentist!",
"Countdown Begins",
"It's Bad Luck To See A Spider At Night",
"Once You're Entangled In A Spiderweb, It's Hard To Get It Off",
"It's The Irresponsible One Who's Scary When Pissed",
"The More Precious The Burden, The Heavier And More Difficult It Is To Shoulder It",
"Watch Out For A Set Of Women And A Drink",
"Screw Popularity Votes",
"Popularity Polls Can Burn In Hell",
"Popularity Polls Can...",
"Hometowns And Boobs Are Best Thought From Afar""The Whole Peeing On A Bee Sting Is A Myth. You'll Get Germs, So Don't Do It!!",
"Beware Of Foreshadows",
"It's Goodbye Once A Flag Is Set",
"An Observation Journal Should Be Seen Through To The Very End",
"It's Better To Take Care Of This Year's Business Within The Year, But Once The Year Is About To End, You Figure That You Might As Well Put It Off Till Next Year For A Fresh Start. That's How The End Of The Year Goes""Radio Exercises Are Socials For Boys And Girls",
"When Looking For Something, Try Using Its Perspective",
"Freedom Means To Live True To Yourself, Not Without Law!",
"Kabukicho Stray Cat Blues",
"Cooking Is About Guts",
"Whenever I Hear Leviathan, I Think Of Sazae-san. Stupid Me!!",
"Not Losing To The Rain",
"Not Losing To The Wind",
"Not Losing To The Storm",
"Never Losing That Smile",
"That's How I Wish To Be, Beautiful And Strong",
"Santa Claus Red Is Blood Red",
"Everybody's A Santa",
"Everyone Looks a Little Grown up after Spring Break",
"Everyone Looks Pretty Grown up after Summer Break",
"Use a Calligraphy Pen for New Year's Cards""The Heart Comes before Chocolate",
"Meals Should Be Balanced""We Are All Warriors in the Battle against Fate",
"It's Too Confusing When Talking about the Poster Girl for a Poster Store, So Call Her a Sandwich Board",
"Glasses Are Part of the Soul",
"Glasses Prevent You from Seeing Certain Things",
"Nothing Lasts Forever, including Parents, Money, Youth, Your Room, Dress Shirts, Me, You, and the Gintama Anime",
"A Lawless Town Tends to Attract a Bunch of Whoohooey Folk",
"Ghosts Aren't the Only Ones Who Run Wild around Graveyards",
"Chains of a Warrior",
"Iron Town",
"'Tis an Honor!",
"Odds or Evens",
"I Can't Remember a Damn Thing about the Factory Tour",
"What Happens Twice Can Happen Thrice",
"The Claws of a Crab Can Snip through a Friendship",
"People Forget to Return Stuff All the Time without Even Realizing It""We Ended Kind of Early So We're Gonna Start the Next Episode (Take Two)",
"The Bathhouse, Where You're Naked in Body and Soul",
"Jugem",
"The Name Reveals the Person",
"The Man's Household Situation Is Hard, His Heart Is Soft",
"Blue and Red Ecstasy",
"So in the Second Season of Prison Break, They've Already Broken out of Prison, but the Name Works Once You Realize That Society Is a Prison",
"Everybody Loves Pajamas",
"Speaking of Crossovers, Don't Forget about Alien vs. Predator",
"Love Is Neither plus Nor Minus",
"Making It through Love",
"It Would Take Too Much Effort to Make This Title Sound like a Text Message Subject",
"When You Go to a Funeral for the First Time, You're Surprised by How Happy the People Are",
"The People You Tend to Forget Tend to Show up after You Forget Them",
"Space Ururun Homestay",
"Piggy Banks and Trash Cans",
"Empty Planet",
"Don't Say Goodbye Lionel",
"Please Take Me Skiing",
"A Vacation in Disorientation",
"You Know Those Year-End Parties Where You Keep Drinking until You've Forgotten Everything That Happened the past Year? There Are a Few Things You're Not Supposed to Forget",
"People Can Only Live by Forgetting the Bad",
"We Are All Hosts, in Capital Letters",
"Girls like Vegeta, Guys like Piccolo",
"Draw Your Life on the Canvas We Call Manga",
"Check It Out!!",
"Thorny and Rosy",
"Festival of Thornies",
"Letter from Thorny",
"Madaodog Madaonaire",
"Presents Are Meant to Be Given Early",
"New Year's Envelopes Are Perfect for Dirty Jokes",
"When Sleeping under a Kotatsu, Make Sure You Don't Burn Your Balls",
"We're Sorry",
"Nobody with Natural Straight Hair Can Be That Bad/Nobody with Straight Blond Hair Can Be That Good",
"Kintoki and Gintoki",
"Kin-san's Kintama",
"The Meaning of a Main Character",
"Courtesan Turns the Tables",
"Inside the Palace!!",
"Five Pinkies",
"Pinky Swear",
"Unsetting Moon",
"Sound Of Beam Can Pierce Heart Of Everyone",
"Two Brothers",
"Liquor and Gasoline, Smiles and Tears",
"Dog Food Doesn't Have As Much Flavor As You'd Think",
"You can never Pause at the Perfect Time",
"Even a Matsui Stick Can't Handle Some Kinds of Dirt",
"An Inspector's Love begins with an Inspection",
"Forget Dates, Remember People""You Can Hide Your Porn Mags But You Can't Hide Your ***",
"A Mirror Provides a Frozen Reflection of Both Your Beautiful and Ugly Sides""Nobody Likes the Photo on Their License",
"Arriving Late to a Reunion Makes it Hard to Enter",
"A Reunion Also Brings to the Surface Things You Don't Want to Remember",
"When Compared to Time in the Heavens, Fifty Years of Human Life Resembles Naught but Dreams and Lottery Tickets",
"Guys With Big Nostrils Also Have Big Imaginations""You Never Accept a New Sentai Series at the Start, But By the Final Episode, You Don't Want It to End",
"9 + 1 = Yagyu Jyubei",
"Calories Come Back to Bite You Just When You've Forgotten About Them",
"10 - 1 =",
"All Mothers Pack Too Much Food Into a Lunch Box and Ruin the Shape",
"The Reaper by Day and the Reaper by Night",
"Human or Demon?",
"Farewell, Reaper",
"A Phoenix Rises from the Ashes Over and Over",
"Amen",
"Being a Leader Is Tough",
"Love Is a Roach Motel",
"A Sizzle Summer""A Nothing Summer, 2015",
"I'm the Mayo Guy, and He's the Sweet Tooth",
"I'm a Failure as a Leader and He's Also a Failure as a Leader",
"I'm Yorozuya and He's Shinsengumi",
"Always Leave Enough Room for Fifty Million in Your Bag",
"Always Leave Enough Room for Pebbles in Your Bag",
"Style Goes Out of Fashion the Moment It's Put Into Words""There Are Two Types of People In This World: Those Who Yell Out Their Attack Names, and Those Who Don't",
"The Two Apes",
"Afros of Life and Death",
"Afuro and Wolfro",
"Take the Initial Premise Lightly, and It'll Cost You",
"Keep Your Farewells Short",
"One Editor Is Enough""The G-Pen Is Capricious, and the Maru Pen Is Stubborn",
"Strike When the Sword and Overlord are Hot""Oil Rain",
"Shogun of Light and Shadow",
"Ninja Village",
"Ninja Soul",
"And Then There Were Five",
"Those Who Protect Against All Odds",
"Sworn Enemy",
"The Crows Caw After The Battle Ends",
"Farewell, Buddy",
"The Day the Demon Cried",
"Heroes Always Arrive Fashionably Late",
"Lost and Found",
"Prison Break""Essay Manga Are Easy to Animate",
"Stray Dogs",
"Undelivered Mail",
"Karma",
"Nobume",
"Farewell Shinsengumi",
"The Monster and the Monster's Child",
"Leave Letter",
"The Song of Samurai",
"Zura",
"The Two Fools",
"Ten Years",
"Paths",
"Master of Kouan",
"The Lost Rabbit",
"Siblings",
"First Student",
"Hope",
"The Stairs to Adulthood May Not Always Lead Up",
"My Bald Dad, My Light-Haired Dad, and My Dad's Glasses",
"A Bowl of Ramen",
"A Family",
"Life, Death, and Shades""All the Answers Can Be Found in the Field",
"3000 Leagues in Search of a Scabbard",
"The Super Sadist and the Super Sadist",
"The Strongest Sword, and the Dullest Sword",
"Wash Your Hands Before a Handshake",
"Diamonds are Unscratchable",
"An Idol's Badge of Honor",
"The Line Between Godlike Games and Shitty Games Is Paper-Thin""Glasses Are a Part of the Soul",
"Guardian Spirits Are Also a Part of the Soul",
"Try As You Might to Make a Natural Perm Go Away, It Will Always Return",
"Flavoring Is Best in Small Quantities",
"A Delinquent's Kid Has Long Neck Hair",
"The Line Between Tenacious and Annoying is Paper-Thin",
"Geezers Carve the Things They Shouldn't Forget into Their Wrinkles",
"Machines That Pick Up Useless Habits Are Called People",
"Men Must Live Not Long or Thick, but Hard",
"Ogres Are Weak Against Tiny Heroes Like the Inch-High Samurai",
"Bragging About Your Own Heroic Deeds Will Make People Hate You, so Make Others Do It For You",
"Jump and Power Creep Go Hand-in-Hand",
"Peace and Destruction Are Two Sides of the Same Coin",
"Bushido Is Found One Second Before Death",
"The Evildoers Who Do Good",
"Rabbits Leap Higher on Moonlit Nights",
"Making a Dull World Interesting",
"Do Something Uncharacteristic, and Something Uncharacteristic Will Happen",
"Countless Kings",
"The Unemployed Cannot Be Stained By Anything",
"Always Hold On to Your Trump Cards",
"The Creatures Known as Humanity",
"Sign",
"Specter",
"Two in Girl Years Is Equal to Ten in Man Years",
"Salvation",
"Dun Dun",
"There Are Lines Even Villains Can't Cross""Gintama Final Ending Scamming Trial",
"Smoke Rises in Places Without Love",
"Gintama",
"White Demon's Birth",
"The Input of This Super Move is Too Hard and I Can't Pull It Off",
"Delicious goods are preempted after being postponed, so be sure to eat them first",
"Gintama: The Movie: Benizakura Chapter",
"Gintama: The Movie: The Final Chapter: Be Forever Yorozuya"]
